// File generated from our OpenAPI spec by Stainless.

package com.revenium_metering.api.models.ai

import kotlin.test.assertNotNull
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Disabled
import org.junit.jupiter.api.Test

internal class AiCreateCompletionParamsTest {

    @Disabled("skipped: tests are disabled for the time being")
    @Test
    fun create() {
        AiCreateCompletionParams.builder()
            .cacheCreationTokenCount(1300L)
            .cacheReadTokenCount(1300L)
            .completionStartTime("2025-03-02T15:04:05Z")
            .costType(AiCreateCompletionParams.CostType.AI)
            .inputTokenCost(12.34)
            .inputTokenCount(50L)
            .model("gpt4")
            .outputTokenCost(12.34)
            .outputTokenCount(150L)
            .provider("OpenAI")
            .reasoningTokenCount(1300L)
            .requestDuration(1000L)
            .requestTime("2025-03-02T15:04:05Z")
            .responseTime("2025-03-02T15:04:06Z")
            .stopReason(AiCreateCompletionParams.StopReason.END)
            .totalCost(12.34)
            .totalTokenCount(200L)
            .transactionId("123e4567-e89b-12d3-a456-426614174000")
            .agent("Bishop")
            .aiProviderKeyName("Production Key (OpenAI)")
            .apiKey("apiKey")
            .organizationId("org-123")
            .productId("Free Trial")
            .sourceId("source-123")
            .subscriberIdentity("ash")
            .subscriptionId("subscr-456")
            .taskId("task-123")
            .taskType("completion")
            .traceId("123e4567-e89b-12d3-a456-426614174000")
            .build()
    }

    @Disabled("skipped: tests are disabled for the time being")
    @Test
    fun body() {
        val params =
            AiCreateCompletionParams.builder()
                .cacheCreationTokenCount(1300L)
                .cacheReadTokenCount(1300L)
                .completionStartTime("2025-03-02T15:04:05Z")
                .costType(AiCreateCompletionParams.CostType.AI)
                .inputTokenCost(12.34)
                .inputTokenCount(50L)
                .model("gpt4")
                .outputTokenCost(12.34)
                .outputTokenCount(150L)
                .provider("OpenAI")
                .reasoningTokenCount(1300L)
                .requestDuration(1000L)
                .requestTime("2025-03-02T15:04:05Z")
                .responseTime("2025-03-02T15:04:06Z")
                .stopReason(AiCreateCompletionParams.StopReason.END)
                .totalCost(12.34)
                .totalTokenCount(200L)
                .transactionId("123e4567-e89b-12d3-a456-426614174000")
                .agent("Bishop")
                .aiProviderKeyName("Production Key (OpenAI)")
                .apiKey("apiKey")
                .organizationId("org-123")
                .productId("Free Trial")
                .sourceId("source-123")
                .subscriberIdentity("ash")
                .subscriptionId("subscr-456")
                .taskId("task-123")
                .taskType("completion")
                .traceId("123e4567-e89b-12d3-a456-426614174000")
                .build()

        val body = params._body()

        assertNotNull(body)
        assertThat(body.cacheCreationTokenCount()).isEqualTo(1300L)
        assertThat(body.cacheReadTokenCount()).isEqualTo(1300L)
        assertThat(body.completionStartTime()).isEqualTo("2025-03-02T15:04:05Z")
        assertThat(body.costType()).isEqualTo(AiCreateCompletionParams.CostType.AI)
        assertThat(body.inputTokenCost()).isEqualTo(12.34)
        assertThat(body.inputTokenCount()).isEqualTo(50L)
        assertThat(body.model()).isEqualTo("gpt4")
        assertThat(body.outputTokenCost()).isEqualTo(12.34)
        assertThat(body.outputTokenCount()).isEqualTo(150L)
        assertThat(body.provider()).isEqualTo("OpenAI")
        assertThat(body.reasoningTokenCount()).isEqualTo(1300L)
        assertThat(body.requestDuration()).isEqualTo(1000L)
        assertThat(body.requestTime()).isEqualTo("2025-03-02T15:04:05Z")
        assertThat(body.responseTime()).isEqualTo("2025-03-02T15:04:06Z")
        assertThat(body.stopReason()).isEqualTo(AiCreateCompletionParams.StopReason.END)
        assertThat(body.totalCost()).isEqualTo(12.34)
        assertThat(body.totalTokenCount()).isEqualTo(200L)
        assertThat(body.transactionId()).isEqualTo("123e4567-e89b-12d3-a456-426614174000")
        assertThat(body.agent()).contains("Bishop")
        assertThat(body.aiProviderKeyName()).contains("Production Key (OpenAI)")
        assertThat(body.apiKey()).contains("apiKey")
        assertThat(body.organizationId()).contains("org-123")
        assertThat(body.productId()).contains("Free Trial")
        assertThat(body.sourceId()).contains("source-123")
        assertThat(body.subscriberIdentity()).contains("ash")
        assertThat(body.subscriptionId()).contains("subscr-456")
        assertThat(body.taskId()).contains("task-123")
        assertThat(body.taskType()).contains("completion")
        assertThat(body.traceId()).contains("123e4567-e89b-12d3-a456-426614174000")
    }

    @Disabled("skipped: tests are disabled for the time being")
    @Test
    fun bodyWithoutOptionalFields() {
        val params =
            AiCreateCompletionParams.builder()
                .cacheCreationTokenCount(1300L)
                .cacheReadTokenCount(1300L)
                .completionStartTime("2025-03-02T15:04:05Z")
                .costType(AiCreateCompletionParams.CostType.AI)
                .inputTokenCost(12.34)
                .inputTokenCount(50L)
                .model("gpt4")
                .outputTokenCost(12.34)
                .outputTokenCount(150L)
                .provider("OpenAI")
                .reasoningTokenCount(1300L)
                .requestDuration(1000L)
                .requestTime("2025-03-02T15:04:05Z")
                .responseTime("2025-03-02T15:04:06Z")
                .stopReason(AiCreateCompletionParams.StopReason.END)
                .totalCost(12.34)
                .totalTokenCount(200L)
                .transactionId("123e4567-e89b-12d3-a456-426614174000")
                .build()

        val body = params._body()

        assertNotNull(body)
        assertThat(body.cacheCreationTokenCount()).isEqualTo(1300L)
        assertThat(body.cacheReadTokenCount()).isEqualTo(1300L)
        assertThat(body.completionStartTime()).isEqualTo("2025-03-02T15:04:05Z")
        assertThat(body.costType()).isEqualTo(AiCreateCompletionParams.CostType.AI)
        assertThat(body.inputTokenCost()).isEqualTo(12.34)
        assertThat(body.inputTokenCount()).isEqualTo(50L)
        assertThat(body.model()).isEqualTo("gpt4")
        assertThat(body.outputTokenCost()).isEqualTo(12.34)
        assertThat(body.outputTokenCount()).isEqualTo(150L)
        assertThat(body.provider()).isEqualTo("OpenAI")
        assertThat(body.reasoningTokenCount()).isEqualTo(1300L)
        assertThat(body.requestDuration()).isEqualTo(1000L)
        assertThat(body.requestTime()).isEqualTo("2025-03-02T15:04:05Z")
        assertThat(body.responseTime()).isEqualTo("2025-03-02T15:04:06Z")
        assertThat(body.stopReason()).isEqualTo(AiCreateCompletionParams.StopReason.END)
        assertThat(body.totalCost()).isEqualTo(12.34)
        assertThat(body.totalTokenCount()).isEqualTo(200L)
        assertThat(body.transactionId()).isEqualTo("123e4567-e89b-12d3-a456-426614174000")
    }
}
