// File generated from our OpenAPI spec by Stainless.

package com.revenium_metering.api.models.ai

import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class AiCreateCompletionParamsTest {

    @Test
    fun create() {
        AiCreateCompletionParams.builder()
            .completionStartTime("2025-10-17T17:35:00Z")
            .costType(AiCreateCompletionParams.CostType.AI)
            .inputTokenCount(100L)
            .isStreamed(false)
            .model("gpt-4")
            .outputTokenCount(150L)
            .provider("OpenAI")
            .requestDuration(2000L)
            .requestTime("2025-10-17T17:35:00Z")
            .responseTime("2025-10-17T17:35:02Z")
            .stopReason(AiCreateCompletionParams.StopReason.END)
            .totalTokenCount(250L)
            .agent("marketing-agent")
            .cacheCreationTokenCost(0.0037)
            .cacheCreationTokenCount(1300L)
            .cacheReadTokenCost(0.0001)
            .cacheReadTokenCount(1300L)
            .errorReason("Rate limit exceeded for model gpt-4")
            .inputTokenCost(0.0015)
            .mediationLatency(45L)
            .middlewareSource("revenium-openai-python-v1.2.3")
            .modelSource("LITELLM")
            .operationType(AiCreateCompletionParams.OperationType.CHAT)
            .organizationId("organizationId-123456")
            .outputTokenCost(0.006)
            .productId("Free Trial")
            .reasoningTokenCount(1300L)
            .responseQualityScore(85.5)
            .subscriber(
                AiCreateCompletionParams.Subscriber.builder()
                    .id("subscriberId-123456")
                    .credential(
                        AiCreateCompletionParams.Subscriber.Credential.builder()
                            .name("OpenAI Key (Production)")
                            .value("pk-1234567")
                            .build()
                    )
                    .email("user@example.com")
                    .build()
            )
            .subscriptionId("subscriptionId-456789")
            .systemFingerprint("fp_44z789a1c23def456gh7890ijkl1234mnopq567rstuv8910wxyz")
            .taskType("code-generation")
            .temperature(0.7)
            .timeToFirstToken(245L)
            .totalCost(0.0213)
            .traceId("123e4567-e89b-12d3-a456-426614174000")
            .transactionId("txn-test-001")
            .build()
    }

    @Test
    fun body() {
        val params =
            AiCreateCompletionParams.builder()
                .completionStartTime("2025-10-17T17:35:00Z")
                .costType(AiCreateCompletionParams.CostType.AI)
                .inputTokenCount(100L)
                .isStreamed(false)
                .model("gpt-4")
                .outputTokenCount(150L)
                .provider("OpenAI")
                .requestDuration(2000L)
                .requestTime("2025-10-17T17:35:00Z")
                .responseTime("2025-10-17T17:35:02Z")
                .stopReason(AiCreateCompletionParams.StopReason.END)
                .totalTokenCount(250L)
                .agent("marketing-agent")
                .cacheCreationTokenCost(0.0037)
                .cacheCreationTokenCount(1300L)
                .cacheReadTokenCost(0.0001)
                .cacheReadTokenCount(1300L)
                .errorReason("Rate limit exceeded for model gpt-4")
                .inputTokenCost(0.0015)
                .mediationLatency(45L)
                .middlewareSource("revenium-openai-python-v1.2.3")
                .modelSource("LITELLM")
                .operationType(AiCreateCompletionParams.OperationType.CHAT)
                .organizationId("organizationId-123456")
                .outputTokenCost(0.006)
                .productId("Free Trial")
                .reasoningTokenCount(1300L)
                .responseQualityScore(85.5)
                .subscriber(
                    AiCreateCompletionParams.Subscriber.builder()
                        .id("subscriberId-123456")
                        .credential(
                            AiCreateCompletionParams.Subscriber.Credential.builder()
                                .name("OpenAI Key (Production)")
                                .value("pk-1234567")
                                .build()
                        )
                        .email("user@example.com")
                        .build()
                )
                .subscriptionId("subscriptionId-456789")
                .systemFingerprint("fp_44z789a1c23def456gh7890ijkl1234mnopq567rstuv8910wxyz")
                .taskType("code-generation")
                .temperature(0.7)
                .timeToFirstToken(245L)
                .totalCost(0.0213)
                .traceId("123e4567-e89b-12d3-a456-426614174000")
                .transactionId("txn-test-001")
                .build()

        val body = params._body()

        assertThat(body.completionStartTime()).isEqualTo("2025-10-17T17:35:00Z")
        assertThat(body.costType()).isEqualTo(AiCreateCompletionParams.CostType.AI)
        assertThat(body.inputTokenCount()).isEqualTo(100L)
        assertThat(body.isStreamed()).isEqualTo(false)
        assertThat(body.model()).isEqualTo("gpt-4")
        assertThat(body.outputTokenCount()).isEqualTo(150L)
        assertThat(body.provider()).isEqualTo("OpenAI")
        assertThat(body.requestDuration()).isEqualTo(2000L)
        assertThat(body.requestTime()).isEqualTo("2025-10-17T17:35:00Z")
        assertThat(body.responseTime()).isEqualTo("2025-10-17T17:35:02Z")
        assertThat(body.stopReason()).isEqualTo(AiCreateCompletionParams.StopReason.END)
        assertThat(body.totalTokenCount()).isEqualTo(250L)
        assertThat(body.agent()).contains("marketing-agent")
        assertThat(body.cacheCreationTokenCost()).contains(0.0037)
        assertThat(body.cacheCreationTokenCount()).contains(1300L)
        assertThat(body.cacheReadTokenCost()).contains(0.0001)
        assertThat(body.cacheReadTokenCount()).contains(1300L)
        assertThat(body.errorReason()).contains("Rate limit exceeded for model gpt-4")
        assertThat(body.inputTokenCost()).contains(0.0015)
        assertThat(body.mediationLatency()).contains(45L)
        assertThat(body.middlewareSource()).contains("revenium-openai-python-v1.2.3")
        assertThat(body.modelSource()).contains("LITELLM")
        assertThat(body.operationType()).contains(AiCreateCompletionParams.OperationType.CHAT)
        assertThat(body.organizationId()).contains("organizationId-123456")
        assertThat(body.outputTokenCost()).contains(0.006)
        assertThat(body.productId()).contains("Free Trial")
        assertThat(body.reasoningTokenCount()).contains(1300L)
        assertThat(body.responseQualityScore()).contains(85.5)
        assertThat(body.subscriber())
            .contains(
                AiCreateCompletionParams.Subscriber.builder()
                    .id("subscriberId-123456")
                    .credential(
                        AiCreateCompletionParams.Subscriber.Credential.builder()
                            .name("OpenAI Key (Production)")
                            .value("pk-1234567")
                            .build()
                    )
                    .email("user@example.com")
                    .build()
            )
        assertThat(body.subscriptionId()).contains("subscriptionId-456789")
        assertThat(body.systemFingerprint())
            .contains("fp_44z789a1c23def456gh7890ijkl1234mnopq567rstuv8910wxyz")
        assertThat(body.taskType()).contains("code-generation")
        assertThat(body.temperature()).contains(0.7)
        assertThat(body.timeToFirstToken()).contains(245L)
        assertThat(body.totalCost()).contains(0.0213)
        assertThat(body.traceId()).contains("123e4567-e89b-12d3-a456-426614174000")
        assertThat(body.transactionId()).contains("txn-test-001")
    }

    @Test
    fun bodyWithoutOptionalFields() {
        val params =
            AiCreateCompletionParams.builder()
                .completionStartTime("2025-10-17T17:35:00Z")
                .costType(AiCreateCompletionParams.CostType.AI)
                .inputTokenCount(100L)
                .isStreamed(false)
                .model("gpt-4")
                .outputTokenCount(150L)
                .provider("OpenAI")
                .requestDuration(2000L)
                .requestTime("2025-10-17T17:35:00Z")
                .responseTime("2025-10-17T17:35:02Z")
                .stopReason(AiCreateCompletionParams.StopReason.END)
                .totalTokenCount(250L)
                .build()

        val body = params._body()

        assertThat(body.completionStartTime()).isEqualTo("2025-10-17T17:35:00Z")
        assertThat(body.costType()).isEqualTo(AiCreateCompletionParams.CostType.AI)
        assertThat(body.inputTokenCount()).isEqualTo(100L)
        assertThat(body.isStreamed()).isEqualTo(false)
        assertThat(body.model()).isEqualTo("gpt-4")
        assertThat(body.outputTokenCount()).isEqualTo(150L)
        assertThat(body.provider()).isEqualTo("OpenAI")
        assertThat(body.requestDuration()).isEqualTo(2000L)
        assertThat(body.requestTime()).isEqualTo("2025-10-17T17:35:00Z")
        assertThat(body.responseTime()).isEqualTo("2025-10-17T17:35:02Z")
        assertThat(body.stopReason()).isEqualTo(AiCreateCompletionParams.StopReason.END)
        assertThat(body.totalTokenCount()).isEqualTo(250L)
    }
}
