// File generated from our OpenAPI spec by Stainless.

package io.revenium.metering.models.ai

import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class AiCreateCompletionParamsTest {

    @Test
    fun create() {
        AiCreateCompletionParams.builder()
            .completionStartTime("2025-03-02T15:04:05Z")
            .costType(AiCreateCompletionParams.CostType.AI)
            .inputTokenCount(50L)
            .isStreamed(false)
            .model("gpt4")
            .outputTokenCount(150L)
            .provider("OpenAI")
            .requestDuration(1000L)
            .requestTime("2025-03-02T15:04:05Z")
            .responseTime("2025-03-02T15:04:06Z")
            .stopReason(AiCreateCompletionParams.StopReason.END)
            .totalTokenCount(200L)
            .transactionId("123e4567-e89b-12d3-a456-426614174000")
            .agent("Bishop")
            .cacheCreationTokenCount(1300L)
            .cacheReadTokenCount(1300L)
            .errorReason("key not allowed to access model")
            .inputTokenCost(12.34)
            .mediationLatency(1000L)
            .modelSource("ANTHROPIC")
            .operationType(AiCreateCompletionParams.OperationType.CHAT)
            .organizationId("org-123")
            .outputTokenCost(12.34)
            .productId("Free Trial")
            .reasoningTokenCount(1300L)
            .responseQualityScore(45.0)
            .subscriberCredential("asd-123")
            .subscriberCredentialName("OpenAI Key (Production)")
            .subscriberEmail("user@example.com")
            .subscriberId("user-123")
            .subscriptionId("subscr-456")
            .systemFingerprint("fp_44z789a1c23def456gh7890ijkl1234mnopq567rstuv8910wxyz")
            .taskType("completion")
            .temperature(0.78)
            .timeToFirstToken(10200L)
            .totalCost(12.34)
            .traceId("123e4567-e89b-12d3-a456-426614174000")
            .build()
    }

    @Test
    fun body() {
        val params =
            AiCreateCompletionParams.builder()
                .completionStartTime("2025-03-02T15:04:05Z")
                .costType(AiCreateCompletionParams.CostType.AI)
                .inputTokenCount(50L)
                .isStreamed(false)
                .model("gpt4")
                .outputTokenCount(150L)
                .provider("OpenAI")
                .requestDuration(1000L)
                .requestTime("2025-03-02T15:04:05Z")
                .responseTime("2025-03-02T15:04:06Z")
                .stopReason(AiCreateCompletionParams.StopReason.END)
                .totalTokenCount(200L)
                .transactionId("123e4567-e89b-12d3-a456-426614174000")
                .agent("Bishop")
                .cacheCreationTokenCount(1300L)
                .cacheReadTokenCount(1300L)
                .errorReason("key not allowed to access model")
                .inputTokenCost(12.34)
                .mediationLatency(1000L)
                .modelSource("ANTHROPIC")
                .operationType(AiCreateCompletionParams.OperationType.CHAT)
                .organizationId("org-123")
                .outputTokenCost(12.34)
                .productId("Free Trial")
                .reasoningTokenCount(1300L)
                .responseQualityScore(45.0)
                .subscriberCredential("asd-123")
                .subscriberCredentialName("OpenAI Key (Production)")
                .subscriberEmail("user@example.com")
                .subscriberId("user-123")
                .subscriptionId("subscr-456")
                .systemFingerprint("fp_44z789a1c23def456gh7890ijkl1234mnopq567rstuv8910wxyz")
                .taskType("completion")
                .temperature(0.78)
                .timeToFirstToken(10200L)
                .totalCost(12.34)
                .traceId("123e4567-e89b-12d3-a456-426614174000")
                .build()

        val body = params._body()

        assertThat(body.completionStartTime()).isEqualTo("2025-03-02T15:04:05Z")
        assertThat(body.costType()).isEqualTo(AiCreateCompletionParams.CostType.AI)
        assertThat(body.inputTokenCount()).isEqualTo(50L)
        assertThat(body.isStreamed()).isEqualTo(false)
        assertThat(body.model()).isEqualTo("gpt4")
        assertThat(body.outputTokenCount()).isEqualTo(150L)
        assertThat(body.provider()).isEqualTo("OpenAI")
        assertThat(body.requestDuration()).isEqualTo(1000L)
        assertThat(body.requestTime()).isEqualTo("2025-03-02T15:04:05Z")
        assertThat(body.responseTime()).isEqualTo("2025-03-02T15:04:06Z")
        assertThat(body.stopReason()).isEqualTo(AiCreateCompletionParams.StopReason.END)
        assertThat(body.totalTokenCount()).isEqualTo(200L)
        assertThat(body.transactionId()).isEqualTo("123e4567-e89b-12d3-a456-426614174000")
        assertThat(body.agent()).contains("Bishop")
        assertThat(body.cacheCreationTokenCount()).contains(1300L)
        assertThat(body.cacheReadTokenCount()).contains(1300L)
        assertThat(body.errorReason()).contains("key not allowed to access model")
        assertThat(body.inputTokenCost()).contains(12.34)
        assertThat(body.mediationLatency()).contains(1000L)
        assertThat(body.modelSource()).contains("ANTHROPIC")
        assertThat(body.operationType()).contains(AiCreateCompletionParams.OperationType.CHAT)
        assertThat(body.organizationId()).contains("org-123")
        assertThat(body.outputTokenCost()).contains(12.34)
        assertThat(body.productId()).contains("Free Trial")
        assertThat(body.reasoningTokenCount()).contains(1300L)
        assertThat(body.responseQualityScore()).contains(45.0)
        assertThat(body.subscriberCredential()).contains("asd-123")
        assertThat(body.subscriberCredentialName()).contains("OpenAI Key (Production)")
        assertThat(body.subscriberEmail()).contains("user@example.com")
        assertThat(body.subscriberId()).contains("user-123")
        assertThat(body.subscriptionId()).contains("subscr-456")
        assertThat(body.systemFingerprint())
            .contains("fp_44z789a1c23def456gh7890ijkl1234mnopq567rstuv8910wxyz")
        assertThat(body.taskType()).contains("completion")
        assertThat(body.temperature()).contains(0.78)
        assertThat(body.timeToFirstToken()).contains(10200L)
        assertThat(body.totalCost()).contains(12.34)
        assertThat(body.traceId()).contains("123e4567-e89b-12d3-a456-426614174000")
    }

    @Test
    fun bodyWithoutOptionalFields() {
        val params =
            AiCreateCompletionParams.builder()
                .completionStartTime("2025-03-02T15:04:05Z")
                .costType(AiCreateCompletionParams.CostType.AI)
                .inputTokenCount(50L)
                .isStreamed(false)
                .model("gpt4")
                .outputTokenCount(150L)
                .provider("OpenAI")
                .requestDuration(1000L)
                .requestTime("2025-03-02T15:04:05Z")
                .responseTime("2025-03-02T15:04:06Z")
                .stopReason(AiCreateCompletionParams.StopReason.END)
                .totalTokenCount(200L)
                .transactionId("123e4567-e89b-12d3-a456-426614174000")
                .build()

        val body = params._body()

        assertThat(body.completionStartTime()).isEqualTo("2025-03-02T15:04:05Z")
        assertThat(body.costType()).isEqualTo(AiCreateCompletionParams.CostType.AI)
        assertThat(body.inputTokenCount()).isEqualTo(50L)
        assertThat(body.isStreamed()).isEqualTo(false)
        assertThat(body.model()).isEqualTo("gpt4")
        assertThat(body.outputTokenCount()).isEqualTo(150L)
        assertThat(body.provider()).isEqualTo("OpenAI")
        assertThat(body.requestDuration()).isEqualTo(1000L)
        assertThat(body.requestTime()).isEqualTo("2025-03-02T15:04:05Z")
        assertThat(body.responseTime()).isEqualTo("2025-03-02T15:04:06Z")
        assertThat(body.stopReason()).isEqualTo(AiCreateCompletionParams.StopReason.END)
        assertThat(body.totalTokenCount()).isEqualTo(200L)
        assertThat(body.transactionId()).isEqualTo("123e4567-e89b-12d3-a456-426614174000")
    }
}
